[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[font]
size = 11

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "Full"
dynamic_padding = true
opacity = 0.8
startup_mode = "Windowed"

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Debian",
    "--cd",
    "~"
]